
package l1j.server.swing;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;

import javax.swing.ImageIcon;

import l1j.server.L1DatabaseFactory;
import l1j.server.server.datatables.NpcTable;
import l1j.server.server.datatables.PetTable;
import l1j.server.server.datatables.SkillsTable;
import l1j.server.server.model.L1Clan;
import l1j.server.server.model.L1World;
import l1j.server.server.model.Instance.L1ItemInstance;
import l1j.server.server.model.Instance.L1PcInstance;
import l1j.server.server.model.Warehouse.ClanWarehouse;
import l1j.server.server.model.Warehouse.PrivateWarehouse;
import l1j.server.server.model.Warehouse.WarehouseManager;
import l1j.server.server.templates.L1Npc;
import l1j.server.server.templates.L1Pet;
import l1j.server.server.templates.L1Skills;
import l1j.server.server.utils.SQLUtil;

public class infomation extends javax.swing.JFrame {
    private static int cnt = 0;
    private static final int size = 580;
	private ImageIcon logo =  new ImageIcon("data/img/logo.jpg");			// 讀取管理員圖片
	private ImageIcon king_e;
	
	private L1PcInstance pc;
	private ArrayList<L1ItemInstance> pet;
    /** Creates new form NewJFrame */
    public infomation(L1PcInstance pcc) {
    	pet = new ArrayList<L1ItemInstance>();		
		pc = pcc;
        initComponents();	
        this.setSize(274, this.getHeight()); // 274
        this.setLocation(300, 300);
		this.setResizable(false);
		this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "serial" })

    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        layout1 = new javax.swing.JLayeredPane();
        iframe1 = new javax.swing.JInternalFrame();
        img = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        hp = new javax.swing.JLabel();
        mp = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        mr = new javax.swing.JLabel();
        account2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        level2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hp2 = new javax.swing.JLabel();
        mp2 = new javax.swing.JLabel();
        ac2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jMenuItem1.setText("查看詳情");
        jMenuItem1.setToolTipText("可以放大或縮小信息窗口。");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem1);

        jMenuItem2.setText("重新整理");
        jMenuItem2.setToolTipText("更新信息。");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem2);

        jMenuItem3.setText("結束");
        jMenuItem3.setToolTipText("結束");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem3);

        setTitle("Server Character Intomation");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
		

        iframe1.setForeground(new java.awt.Color(0, 0, 255));
        iframe1.setTitle("Character Infomation");
        iframe1.setToolTipText("角色信息窗口");
        iframe1.setFrameIcon(logo); // NOI18N
        iframe1.setVisible(true);
        iframe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iframe1MouseClicked(evt);
            }
        });

        img.setBackground(new java.awt.Color(0, 0, 0));
        img.setForeground(new java.awt.Color(255, 255, 255));
        img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       String ClassId = "";
        switch(pc.getClassId()){
            case 0: ClassId = "data/img/王子.jpg"; break;
            case 1: ClassId = "data/img/公主.jpg"; break;
            case 20553: ClassId = "data/img/男騎士.jpg"; break;
            case 48: ClassId = "data/img/女騎士.jpg"; break;
            case 138: ClassId = "data/img/男妖精.jpg"; break;
            case 37: ClassId = "data/img/女妖精.jpg"; break;
            case 20278: ClassId = "data/img/男法師.jpg"; break;
            case 20279: ClassId = "data/img/女法師.jpg"; break;
            case 2786: ClassId = "data/img/男黑暗妖精.jpg"; break;
            case 2796: ClassId = "data/img/女黑暗妖精.jpg"; break;
            case 6658: ClassId = "data/img/男龍騎士.jpg"; break;
            case 6661: ClassId = "data/img/女龍騎士.jpg"; break;
            case 6671: ClassId = "data/img/男幻術師.jpg"; break;
            case 6650: ClassId = "data/img/女幻術師.jpg"; break;
            case 20567: ClassId = "data/img/男戰士.jpg"; break;
            case 20577: ClassId = "data/img/女戰士.jpg"; break;
            case 18520: ClassId = "data/img/男劍士.jpg"; break;
            case 18499: ClassId = "data/img/女劍士.jpg"; break;
            case 19296: ClassId = "data/img/男黃金槍騎.jpg"; break;
            case 19299: ClassId = "data/img/女黃金槍騎.jpg"; break;
        
        }
        king_e =  new ImageIcon(ClassId);
       img.setIcon(king_e);
       img.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        img.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        account.setFont(new java.awt.Font("Gulim", 1, 12));
        account.setForeground(new java.awt.Color(0, 0, 255));
        account.setText("帳 號 : ");

        name.setFont(new java.awt.Font("Gulim", 1, 12));
        name.setForeground(new java.awt.Color(0, 0, 255));
        name.setText("角色名稱 : ");

        level.setFont(new java.awt.Font("Gulim", 1, 12));
        level.setForeground(new java.awt.Color(0, 0, 255));
        level.setText("等    級 : ");

        hp.setFont(new java.awt.Font("Gulim", 1, 12));
        hp.setForeground(new java.awt.Color(0, 0, 255));
        hp.setText("體    力 : ");

        mp.setFont(new java.awt.Font("Gulim", 1, 12));
        mp.setForeground(new java.awt.Color(0, 0, 255));
        mp.setText("魔    力 : ");

        ac.setFont(new java.awt.Font("Gulim", 1, 12));
        ac.setForeground(new java.awt.Color(0, 0, 255));
        ac.setText("防禦力 : ");

        mr.setFont(new java.awt.Font("Gulim", 1, 12));
        mr.setForeground(new java.awt.Color(0, 0, 255));
        mr.setText("魔法防禦力 : ");

        account2.setText(pc.getAccountName());

        name2.setText(pc.getName());	
		
        level2.setText(Integer.toString(pc.getLevel()));

        jLabel12.setText("Lv");

        hp2.setText(Integer.toString(pc.getMaxHp()));

        mp2.setText(Integer.toString(pc.getMaxMp()));

        ac2.setText(Integer.toString(pc.getAC().getAc()));

        jLabel16.setText(Integer.toString(pc.getResistance().getMr()));

        jLabel17.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel17.setForeground(new java.awt.Color(0, 153, 51));
        jLabel17.setText("* 角色屬性資訊 *");

        jLabel18.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("力量 : ");

        jLabel19.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("敏捷 : ");

        jLabel20.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("體質 : ");

        jLabel21.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("精神 : ");

        jLabel22.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("智力 : ");

        jLabel23.setFont(new java.awt.Font("Gulim", 1, 12));
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("魅力 : ");

        jLabel24.setText(Integer.toString(pc.getAbility().getStr()));

        jLabel25.setText(Integer.toString(pc.getAbility().getDex()));

        jLabel26.setText(Integer.toString(pc.getAbility().getCon()));

        jLabel27.setText(Integer.toString(pc.getAbility().getWis()));

        jLabel28.setText(Integer.toString(pc.getAbility().getInt()));

        jLabel29.setText(Integer.toString(pc.getAbility().getCha()));

        jLabel2.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));		
		String clas;
        switch(pc.getType()){
            case 0: clas = "王族"; break;
            case 1: clas = "騎士"; break;
            case 2: clas = "妖精"; break;
            case 3: clas = "法師"; break;
            case 4: clas = "黑暗妖精"; break;
            case 5: clas = "龍騎士"; break;
            case 6: clas = "幻術師"; break;
            case 7: clas = "戰士"; break;
            case 8: clas = "劍士"; break;
            case 9: clas = "黃金槍騎"; break;
            default: clas = "(錯誤)"; break;
        }
        jLabel2.setText(clas);

        javax.swing.GroupLayout iframe1Layout = new javax.swing.GroupLayout(iframe1.getContentPane());
        iframe1.getContentPane().setLayout(iframe1Layout);
        iframe1Layout.setHorizontalGroup(
            iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iframe1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iframe1Layout.createSequentialGroup()
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(account)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(account2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(level)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(level2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(hp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hp2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(mp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mp2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(ac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ac2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(mr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105))
                    .addComponent(jLabel17)
                    .addGroup(iframe1Layout.createSequentialGroup()
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)))
                        .addGap(30, 30, 30)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(iframe1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)))))
                .addContainerGap())
        );
        iframe1Layout.setVerticalGroup(
            iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(iframe1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(iframe1Layout.createSequentialGroup()
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(account)
                            .addComponent(account2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(name2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(level)
                            .addComponent(level2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hp)
                            .addComponent(hp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mp)
                            .addComponent(mp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ac)
                            .addComponent(ac2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mr)
                            .addComponent(jLabel16)))
                    .addGroup(iframe1Layout.createSequentialGroup()
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(iframe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        iframe1.setBounds(0, 0, 270, 310);
        layout1.add(iframe1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            iframe1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame1.setTitle("Etc Infomation");
        jInternalFrame1.setToolTipText("其他資訊視窗");
        jInternalFrame1.setFrameIcon(logo); // NOI18N
        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("據點 : ");
        jLabel1.setBounds(10, 90, 70, 15);
        jLayeredPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("血盟帳號 : ");
        jLabel3.setBounds(10, 30, 70, 15);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("血盟盟主 : ");
        jLabel4.setBounds(10, 50, 70, 15);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("所有城堡 : ");
        jLabel5.setBounds(10, 70, 70, 15);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("血盟名稱 : ");
        jLabel6.setBounds(10, 10, 70, 15);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        L1Clan clan = null;        
       if (pc.getClanname() != null){
    	   clan = L1World.getInstance().getClan(pc.getClanid());
       }
		String Castle = "";
		String House = "";
		String ClanName = "";
		String ClanId = "";
		String LeaderName = "";
		if(clan != null){
		  House = mesod(Integer.toString(clan.getHouseId()));
		  ClanName = clan.getClanName();
		  ClanId = Integer.toString(clan.getClanId());
		  LeaderName = clan.getLeaderName();
            switch(clan.getCastleId()){
                case 1: Castle = "肯特城"; break;
                case 2: Castle = "半獸人要塞"; break;
                case 3: Castle = "風木城"; break;
                case 4: Castle = "奇岩城"; break;
                case 5: Castle = "海音城"; break;
                case 6: Castle = "地底城"; break;
                case 7: Castle = "亞丁城"; break;
                case 8: Castle = "迪亞德要塞"; break;
                default: Castle = "(無)"; break;
            }
        }else if(clan == null){
            ClanName = "(無血盟)";
        }
		
        jLabel7.setText(House);
        jLabel7.setBounds(80, 90, 110, 15);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
       
        jLabel8.setText(ClanName);        
        jLabel8.setBounds(80, 10, 110, 15);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
        jLabel9.setText(ClanId);
        jLabel9.setBounds(80, 30, 110, 15);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText(LeaderName);
        jLabel10.setBounds(80, 50, 110, 15);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);		

        jLabel11.setText(Castle);
        jLabel11.setBounds(80, 70, 110, 15);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        
		Object[][] layta1 = new Object[180][4];
		if(clan != null){
		int pp0 = -1;
		ClanWarehouse clanWarehouse = WarehouseManager.getInstance().getClanWarehouse(clan.getClanName());
		for (Object itemObject1 : clanWarehouse.getItems()) {
			L1ItemInstance itemm = (L1ItemInstance) itemObject1;						
			layta1[++pp0][0] = itemm.getName();
			layta1[pp0][1] = itemm.getEnchantLevel();
			if(itemm.getItem().getBless() == 0){layta1[pp0][2] = true;
		} else {
			layta1[pp0][2] = false;
		}			
		layta1[pp0][3] = itemm.getCount();
		}
		}
        jTable5.setModel(new javax.swing.table.DefaultTableModel(layta1,
                new String [] {
                   "名稱", "強化", "祝福", "數量"
                }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jTable5);
        jTable5.getColumnModel().getColumn(0).setResizable(false);
        jTable5.getColumnModel().getColumn(0).setPreferredWidth(220);
        jTable5.getColumnModel().getColumn(1).setResizable(false);
        jTable5.getColumnModel().getColumn(2).setResizable(false);
        jTable5.getColumnModel().getColumn(3).setResizable(false);
       

        jScrollPane5.setBounds(0, 0, 280, 140);
        jLayeredPane3.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(0, 110, 280, 140);
        jLayeredPane2.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab("血盟", jLayeredPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(skills(pc),
            new String [] {
              "技能名稱", "魔法種類"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
					
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        jTabbedPane1.addTab("技能", jScrollPane1);
		Object[][] layta = new Object[180][4];		
		int p = -1;
			for (Object itemObject : pc.getInventory().getItems()) {
			L1ItemInstance itemf = (L1ItemInstance) itemObject;	
			if(itemf.getItem().getItemId() == 40314 || itemf.getItem().getItemId() == 40316){
				pet.add(itemf);
			}
		    layta[++p][0] = itemf.getName();			
			layta[p][1] = itemf.getEnchantLevel();
			if(itemf.getItem().getBless() == 0){layta[p][2] = true;
			}else{layta[p][2] = false;}			
			layta[p][3] = itemf.getCount();
				
		}
			
        jTable2.setModel(new javax.swing.table.DefaultTableModel(layta,           
            new String [] {
               "名稱", "強化", "祝福", "數量"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setResizable(false);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(220);
        jTable2.getColumnModel().getColumn(1).setResizable(false);
        jTable2.getColumnModel().getColumn(2).setResizable(false);
        jTable2.getColumnModel().getColumn(3).setResizable(false);

        jTabbedPane1.addTab("道具", jScrollPane2);
		Object[][] layta2 = new 	Object[180][4];
		int pp = -1;		
		PrivateWarehouse warehouse = WarehouseManager.getInstance().getPrivateWarehouse(pc.getAccountName());
		if(warehouse == null)	return;
	
		for (Object itemObjectr : warehouse.getItems()) {
			L1ItemInstance itemm = (L1ItemInstance) itemObjectr;	
			if(itemm.getItem().getItemId() == 40314 || itemm.getItem().getItemId() == 40316){
				pet.add(itemm);
			}
		layta2[++pp][0] = itemm.getName();
		layta2[pp][1] = itemm.getEnchantLevel();
		if(itemm.getItem().getBless() == 0){layta2[pp][2] = true;
		}else{layta2[pp][2] = false;}			
		layta2[pp][3] = itemm.getCount();
	}

    jTable3.setModel(new javax.swing.table.DefaultTableModel(layta2,           
        new String [] {
           "名稱","強化","祝福","數量"
        }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getColumn(0).setResizable(false);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(220);
        jTable3.getColumnModel().getColumn(1).setResizable(false);
        jTable3.getColumnModel().getColumn(2).setResizable(false);
        jTable3.getColumnModel().getColumn(3).setResizable(false);

        jTabbedPane1.addTab("倉庫", jScrollPane3);
        Object[][] layta4 = new 	Object[100][4];
        int lj = -1;
        for(int i =0; i< pet.size();i++){
        	L1ItemInstance itemv = pet.get(i);
        	L1Pet pett = PetTable.getInstance().getTemplate(itemv.getId());
        	if(pett != null){
        	layta4[++lj][0] = pett.get_name();
        	L1Npc l1npc = NpcTable.getInstance().getTemplate(pett.get_npcid());
        	layta4[lj][1] = l1npc.get_name();        	
        	layta4[lj][2] = pett.get_level();
        	layta4[lj][3] = pett.get_exp();
        	}
        }
        
        

        jTable4.setModel(new javax.swing.table.DefaultTableModel(layta4,          
            new String [] {
               "名稱", "種類", "等級", "經驗值"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);
        jTable4.getColumnModel().getColumn(0).setResizable(false);
		jTable4.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable4.getColumnModel().getColumn(1).setResizable(false);
		jTable4.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable4.getColumnModel().getColumn(2).setResizable(false);
        jTable4.getColumnModel().getColumn(3).setResizable(false);
		jTable4.getColumnModel().getColumn(3).setPreferredWidth(120);

        jTabbedPane1.addTab("寵物", jScrollPane4);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(0, 0, 290, 290);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            jInternalFrame1.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layout1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
            .addComponent(layout1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
		
        pack();
    }// </editor-fold>//GEN-END:initComponents

private void iframe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iframe1MouseClicked
// TODO add your handling code here:
    if(evt.getButton() == evt.BUTTON3){
        popup.show(iframe1, evt.getX(), evt.getY());
    }
}//GEN-LAST:event_iframe1MouseClicked
    /** 放大縮小 */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO 在這裡添加您的處理代碼：
/** 放大 */
        if(cnt == 0){
            jMenuItem1.setText("簡單查看");
            cnt = 1;
            this.setSize(size, this.getHeight());
        } else {
            jMenuItem1.setText("詳細查看");
        cnt = 0;
        this.setSize(274, this.getHeight());
    }
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    /** 伺服器正在運行 */
    if (chocco.serverstart) {
        javax.swing.JOptionPane.showMessageDialog(this, "服務準備中。", "伺服器訊息", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        /** 伺服器未運行 */
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "伺服器未啟動。", "伺服器訊息", javax.swing.JOptionPane.ERROR_MESSAGE);

        private void jMenuItem3ActionPerformed (java.awt.event.ActionEvent evt)
        {//GEN-FIRST:event_jMenuItem2ActionPerformed
            this.setVisible(false);
            chocco.inf = false;
        }

        private String mesod (String id){
            Connection con = null;
            PreparedStatement pstm = null;
            ResultSet rs = null;
            String bong = "";
            try {
                con = L1DatabaseFactory.getInstance().getConnection();
                pstm = con.prepareStatement("SELECT location FROM house WHERE house_id=?");
                pstm.setString(1, id);
                rs = pstm.executeQuery();
                bong = rs.getString("location");
            } catch (Exception e) {
                e.getLocalizedMessage();
            } finally {
                SQLUtil.close(rs);
                SQLUtil.close(pstm);
                SQLUtil.close(con);
            }
            return bong;
        }

        private String[][] skills (L1PcInstance pc){
            Connection con = null;
            PreparedStatement pstm = null;
            ResultSet rs = null;
            String[][] ttl = new String[100][2];
            int i = -1;
            String leaf = "";
            try {
                con = L1DatabaseFactory.getInstance().getConnection();
                pstm = con.prepareStatement("SELECT * FROM character_skills WHERE char_obj_id=? ");
                pstm.setInt(1, pc.getId());
                rs = pstm.executeQuery();
                while (rs.next()) {
                    int skillId = rs.getInt("skill_id");
                    L1Skills l1skills = SkillsTable.getInstance().getTemplate(skillId);
                    ttl[++i][0] = l1skills.getName();
                    if (l1skills.getSkillId() >= 1 && l1skills.getSkillId() <= 80) {
                        leaf = "一般魔法";
                    } else if (l1skills.getSkillId() >= 87 && l1skills.getSkillId() <= 91) {
                        leaf = "騎士魔法";
                    } else if (l1skills.getSkillId() >= 97 && l1skills.getSkillId() <= 111) {
                        leaf = "黑暗妖精魔法";
                    } else if (l1skills.getSkillId() >= 113 && l1skills.getSkillId() <= 120) {
                        leaf = "王族魔法";
                    } else if (l1skills.getSkillId() >= 129 && l1skills.getSkillId() <= 176) {
                        leaf = "妖精魔法";
                    } else if (l1skills.getSkillId() >= 177 && l1skills.getSkillId() <= 200) {
                        leaf = "龍語魔法";
                    } else if (l1skills.getSkillId() >= 201 && l1skills.getSkillId() <= 224) {
                        leaf = "幻術魔法";
                    } else if (l1skills.getSkillId() >= 225 && l1skills.getSkillId() <= 230) {  // 假設法師魔法的技能ID範圍
                        leaf = "法師魔法";
                    } else if (l1skills.getSkillId() >= 231 && l1skills.getSkillId() <= 236) {  // 假設戰士魔法的技能ID範圍
                        leaf = "戰士魔法";
                    } else if (l1skills.getSkillId() >= 237 && l1skills.getSkillId() <= 242) {  // 假設劍士魔法的技能ID範圍
                        leaf = "劍士魔法";
                    } else if (l1skills.getSkillId() >= 243 && l1skills.getSkillId() <= 248) {  // 假設黃金槍騎魔法的技能ID範圍
                        leaf = "黃金槍騎魔法";
                    } else {
                        leaf = "錯誤資訊";
                    }
                    ttl[i][1] = leaf;
                }

            } catch (Exception e) {
                e.getLocalizedMessage();
            } finally {
                SQLUtil.close(rs);
                SQLUtil.close(pstm);
                SQLUtil.close(con);
            }
            return ttl;
        }


        private javax.swing.JLabel ac;
        private javax.swing.JLabel ac2;
        private javax.swing.JLabel account;
        private javax.swing.JLabel account2;
        private javax.swing.JLabel hp;
        private javax.swing.JLabel hp2;
        private javax.swing.JInternalFrame iframe1;
        private javax.swing.JLabel img;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel19;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel20;
        private javax.swing.JLabel jLabel21;
        private javax.swing.JLabel jLabel22;
        private javax.swing.JLabel jLabel23;
        private javax.swing.JLabel jLabel24;
        private javax.swing.JLabel jLabel25;
        private javax.swing.JLabel jLabel26;
        private javax.swing.JLabel jLabel27;
        private javax.swing.JLabel jLabel28;
        private javax.swing.JLabel jLabel29;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JLayeredPane jLayeredPane1;
        private javax.swing.JLayeredPane jLayeredPane2;
        private javax.swing.JLayeredPane jLayeredPane3;
        private javax.swing.JMenuItem jMenuItem1;
        private javax.swing.JMenuItem jMenuItem2;
        private javax.swing.JMenuItem jMenuItem3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTable jTable3;
        private javax.swing.JTable jTable4;
        private javax.swing.JTable jTable5;
        private javax.swing.JLayeredPane layout1;
        private javax.swing.JLabel level;
        private javax.swing.JLabel level2;
        private javax.swing.JLabel mp;
        private javax.swing.JLabel mp2;
        private javax.swing.JLabel mr;
        private javax.swing.JLabel name;
        private javax.swing.JLabel name2;
        private javax.swing.JPopupMenu popup;

    }
}}
